# Validate that a pull request stays in scope. Run in CI on every pull
# request that touches themes/, generated output or the scripts.
#
# A theme PR (title tagged "theme:" or any change under themes/) must have a
# "theme:" title and change nothing outside themes/, so it can't quietly
# drag in changes to tools/, data/, or anywhere else in the repo.
#
# Any other PR (code, docs, CI, maintenance) may change the scripts, but
# never the output the generate/ pipeline writes after merge: data/,
# installs/, tools/run.txt and the THEMES array in gogh.sh.
#
# Usage: python tools/validate/validate_pr.py <changed-files-list-path> [<base-ref>]
# Reads the PR title from the PR_TITLE environment variable. With a base ref,
# a gogh.sh change is also checked to leave the THEMES array untouched.

import os
import re
import subprocess
import sys

TITLE_RE = re.compile(r"^\s*themes?:\s*\S", re.IGNORECASE)

# Written by the generate/ pipeline in CI, never by hand
GENERATED_PREFIXES = ("data/", "installs/")
GENERATED_FILES = ("tools/run.txt",)
THEMES_ARRAY_START = "declare -a THEMES=("


def is_theme_pr(title, changed_files):
    return bool(title and TITLE_RE.match(title)) or any(
        f.startswith("themes/") for f in changed_files
    )


def check_title(title):
    if title is None:
        return "PR_TITLE was not set."
    if not TITLE_RE.match(title):
        return (
            f"PR title '{title}' doesn't start with 'theme:'.\n"
            "  Expected something like: 'theme: Add Solarized Midnight'"
        )
    return None


def check_scope(changed_files):
    out_of_scope = [f for f in changed_files if not f.startswith("themes/")]
    if out_of_scope:
        listing = "\n".join(f"  {f}" for f in out_of_scope)
        return (
            f"{len(out_of_scope)} changed file(s) outside themes/:\n{listing}\n"
            "  A theme PR should only add/edit files under themes/."
        )
    return None


def check_generated(changed_files):
    generated = [
        f for f in changed_files
        if f.startswith(GENERATED_PREFIXES) or f in GENERATED_FILES
    ]
    if generated:
        listing = "\n".join(f"  {f}" for f in generated)
        return (
            f"{len(generated)} changed file(s) generated by CI:\n{listing}\n"
            "  These are regenerated automatically after merge -- revert them."
        )
    return None


def themes_array(text):
    """Return the lines of the THEMES array in gogh.sh, or None."""
    lines = text.splitlines()
    for start, line in enumerate(lines):
        if THEMES_ARRAY_START in line:
            for end in range(start + 1, len(lines)):
                if lines[end].strip() == ")":
                    return lines[start:end + 1]
    return None


def check_gogh_theme_list(changed_files, base_ref):
    if "gogh.sh" not in changed_files or base_ref is None:
        return None
    # Compare against where this branch forked, so a THEMES array that the
    # base branch regenerated since then isn't blamed on this PR.
    fork_point = subprocess.run(
        ["git", "merge-base", base_ref, "HEAD"],
        capture_output=True, text=True, check=True,
    ).stdout.strip()
    base = subprocess.run(
        ["git", "show", f"{fork_point}:gogh.sh"],
        capture_output=True, text=True, check=True,
    ).stdout
    with open("gogh.sh") as f:
        head = f.read()
    if themes_array(base) != themes_array(head):
        return (
            "gogh.sh changes the THEMES array.\n"
            "  That list is generated by CI from themes/ after merge -- "
            "revert the array and keep only the code changes."
        )
    return None


if __name__ == "__main__":
    if len(sys.argv) not in (2, 3):
        print("Usage: python tools/validate/validate_pr.py <changed-files-list-path> [<base-ref>]")
        sys.exit(2)

    with open(sys.argv[1]) as f:
        changed_files = [line.strip() for line in f if line.strip()]
    base_ref = sys.argv[2] if len(sys.argv) == 3 else None
    title = os.environ.get("PR_TITLE")

    if is_theme_pr(title, changed_files):
        kind = "theme PR"
        checks = [check_title(title), check_scope(changed_files)]
    else:
        kind = "non-theme PR"
        checks = [
            check_generated(changed_files),
            check_gogh_theme_list(changed_files, base_ref),
        ]
    errors = [error for error in checks if error]

    if errors:
        print(f"❌ PR scope validation failed ({kind}):\n")
        for error in errors:
            print(error, "\n")
        sys.exit(1)

    print(f"✅ PR title and scope look good ({kind}).")
