# .sync.yml

commit_message: "🔁 chore(sync): sync files"

rules:
  - name: "ai-commands"
    source_of_truth:
      branch: "main"
      path: ".opencode/commands/"
    destinations:
      - path: ".claude/commands/"
      - path: ".codex/prompts/"
      - path: ".cursor/commands/"
      - path: ".aider/commands/"
      - path: ".github/prompts/"
      - path: ".crush/commands/"
      - path: ".gemini/commands/"
      - path: ".copilot/commands/"
    branches:
      - "main"
      - "develop"
      - "release"

  - name: "ai-skills"
    source_of_truth:
      branch: "main"
      path: ".skills/"
    destinations:
      - path: ".claude/skills/"
      - path: ".codex/skills/"
      - path: ".cursor/skills/"
      - path: ".aider/skills/"
      - path: ".vscode/skills/"
      - path: ".crush/skills/"
      - path: ".gemini/skills/"
      - path: ".copilot/skills/"
    branches:
      - "main"
      - "develop"
      - "release"
