# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "🚀 - Deploy to GitHub Pages (branch website)"

on:
  workflow_dispatch:
  push:
    branches:
      - main/website

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout website branch
        uses: actions/checkout@v4
        with:
          ref: main/website

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm install
      - run: npm run generate

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .output/public


  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github_pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
